Fix PyTorch+Numpy integration in nightly builds (#752)
Installing mkl-2021.2 renders numpy-11.1 unimportable on Windows:
From https://github.com/pytorch/builder/commit/da1928b8e919c362ada44ef5a9b2e10bc7f518f8
```
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "C:\w\b\windows\conda\envs\py36\lib\site-packages\numpy\__init__.py", line 142, in <module>
      from . import add_newdocs
    File "C:\w\b\windows\conda\envs\py36\lib\site-packages\numpy\add_newdocs.py", line 13, in <module>
      from numpy.lib import add_newdoc
    File "C:\w\b\windows\conda\envs\py36\lib\site-packages\numpy\lib\__init__.py", line 8, in <module>
      from .type_check import *
    File "C:\w\b\windows\conda\envs\py36\lib\site-packages\numpy\lib\type_check.py", line 11, in <module>
      import numpy.core.numeric as _nx
    File "C:\w\b\windows\conda\envs\py36\lib\site-packages\numpy\core\__init__.py", line 14, in <module>
      from . import multiarray
  ImportError: DLL load failed: The specified module could not be found.
  -- Could NOT find NumPy (missing: NUMPY_INCLUDE_DIR NUMPY_VERSION)
```